# Generated by Django 5.2.3 on 2025-06-22 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19)),
                ('card_expiry', models.CharField(max_length=5)),
                ('card_name', models.CharField(max_length=100)),
                ('card_cvv', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_data', to='shop.order')),
            ],
        ),
    ]
